// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartnerCommission.Wallets.Api.Data;

#nullable disable

namespace PartnerCommission.Wallets.Api.Data.Migrations
{
    [DbContext(typeof(WalletsDbContext))]
    [Migration("20260928110817_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerCommission.Wallets.Api.Entities.Wallet", b =>
                {
                    b.Property<string>("UserExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserExternalId");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("PartnerCommission.Wallets.Api.Entities.WalletEntry", b =>
                {
                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccruedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("EventExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UserExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CommissionId");

                    b.HasIndex("Status");

                    b.HasIndex("UserExternalId", "PaidAtUtc");

                    b.HasIndex("UserExternalId", "Status");

                    b.ToTable("wallet_entries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
